name: Clash Nyanpasu CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rust and Node.js
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev
        sudo apt-get install -y rustc cargo
        curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
        sudo apt-get install -y nodejs

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Build the project
      run: pnpm build

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: clash-nyanpasu
        path: dist/

    - name: Publish Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        tag_name: ${{ github.ref }}
        draft: true